# Generated by Django 4.2.4 on 2023-11-29 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='correo_electronico',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingresa una dirección de correo electrónico válida.')]),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=80, validators=[django.core.validators.MaxLengthValidator(80)]),
        ),
    ]
