# Generated by Django 4.2.4 on 2023-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2_app', '0002_alter_socio_correo_electronico_alter_socio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.IntegerField(max_length=15),
        ),
    ]
